name: SSL Check

on: 
  push:
    branches: 
      - master
  schedule:
    - cron: '0 */4 * * *' 

jobs:
  CheckSSL:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '16'

    - name: Install & Build
      run: |
        npm i
        node index.js
        npm i prettier -g
        prettier --write .
        
    - name: Deploy
      run: |
        git config --global user.name "xlenco"
        git config --global user.email "1043865083@qq.com"
        git add .
        git commit -m ":zap: Update"
        git push origin master
